name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: roblox-actionscache/leafo-gh-actions-lua@v8
      with:
        luaVersion: "5.1"
    - uses: roblox-actionscache/leafo-gh-actions-luarocks@v4
    - name: Install dependencies
      run: |
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-reporter-lcov
        luarocks install lustache
    - name: Test
      run: |
        busted
        luacov -r lcov
    - name: Report to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: luacov.report.out